#include $(srctree)/drivers/misc/mediatek/Makefile.custom

MTK_PLATFORM := $(subst ",,$(CONFIG_MTK_PLATFORM))
subdir-ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/$(MTK_PLATFORM)/include
subdir-ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/
subdir-ccflags-y += -I$(srctree)/include/mach/
subdir-ccflags-y += -I$(srctree)/drivers/misc/mediatek/chargepump/inc/
subdir-ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/synaptics_2202/inc/
obj-y	:=  rt4832_driver.o

