include $(srctree)/drivers/misc/mediatek/Makefile.custom

ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/
ccflags-y += -I$(srctree)/include/mach/

obj-y += lgtp_device_mit300.o
obj-y += mit300_fw_upgrade.o
obj-y += mit300_self_diagnostic.o