include $(srctree)/drivers/misc/mediatek/Makefile.custom

ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/
ccflags-y += -I$(srctree)/include/mach/

obj-y += lgtp_device_sn280h.o
obj-y += semisense_misc_driver.o
