include $(srctree)/drivers/misc/mediatek/Makefile.custom

ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/
ccflags-y += -I$(srctree)/include/mach/

obj-y +=  lgtp_device_ft6x36.o
obj-y +=  ft6x06_ex_fun.o
obj-y +=  focaltech_ctl.o

